// SPDX-License-Identifier: AGPL-3.0-or-later

//! Zoo regression tests — validates that the Rust parser handles every model
//! from the BrainChip Akida model zoo.
//!
//! These tests require `.fbz` artifacts on disk (generated by `scripts/export_zoo.py`).
//! Run with: `cargo test --test zoo_regression -- --ignored`

use akida_models::prelude::*;
use std::path::Path;

const ZOO_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../baseCamp/zoo-artifacts");

fn zoo_artifacts_available() -> bool {
    let dir = Path::new(ZOO_DIR);
    dir.is_dir() && dir.read_dir().map_or(false, |mut d| d.any(|e| {
        e.map_or(false, |e| e.path().extension().is_some_and(|ext| ext == "fbz"))
    }))
}

fn collect_fbz_files() -> Vec<std::path::PathBuf> {
    let dir = Path::new(ZOO_DIR);
    let mut files: Vec<_> = std::fs::read_dir(dir)
        .expect("cannot read zoo-artifacts/")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "fbz"))
        .collect();
    files.sort();
    files
}

#[test]
#[ignore = "requires baseCamp/zoo-artifacts/*.fbz (run scripts/export_zoo.py first)"]
fn parse_all_zoo_models() {
    if !zoo_artifacts_available() {
        eprintln!("SKIP: no .fbz files in {ZOO_DIR}");
        return;
    }

    let files = collect_fbz_files();
    assert!(!files.is_empty(), "no .fbz files found in {ZOO_DIR}");

    let mut passed = 0;
    let mut failed = Vec::new();

    for path in &files {
        let name = path.file_name().unwrap().to_string_lossy();
        match Model::from_file(path.to_str().unwrap()) {
            Ok(model) => {
                assert!(model.program_size() > 0, "{name}: empty program");
                assert!(model.layer_count() > 0, "{name}: no layers detected");
                assert!(!model.version().is_empty(), "{name}: no version");
                println!(
                    "  OK  {name:45} {size:>10} bytes  {layers:>2} layers  v{ver}",
                    size = model.program_size(),
                    layers = model.layer_count(),
                    ver = model.version(),
                );
                passed += 1;
            }
            Err(e) => {
                println!("  FAIL {name}: {e}");
                failed.push(format!("{name}: {e}"));
            }
        }
    }

    println!("\n{passed}/{} parsed successfully", files.len());
    assert!(failed.is_empty(), "Failed models:\n  {}", failed.join("\n  "));
}

#[test]
#[ignore = "requires baseCamp/zoo-artifacts/*.fbz"]
fn all_zoo_models_have_weights_or_layers() {
    if !zoo_artifacts_available() {
        return;
    }

    for path in collect_fbz_files() {
        let name = path.file_name().unwrap().to_string_lossy();
        let model = Model::from_file(path.to_str().unwrap())
            .unwrap_or_else(|e| panic!("{name}: {e}"));

        let has_structure = model.layer_count() > 0 || model.total_weight_count() > 0;
        assert!(has_structure, "{name}: no layers AND no weights — likely parser failure");
    }
}

#[test]
#[ignore = "requires baseCamp/zoo-artifacts/*.fbz"]
fn decompressed_size_is_smaller_than_or_equal_to_file() {
    if !zoo_artifacts_available() {
        return;
    }

    for path in collect_fbz_files() {
        let name = path.file_name().unwrap().to_string_lossy();
        let file_size = std::fs::metadata(&path).unwrap().len() as usize;
        let model = Model::from_file(path.to_str().unwrap())
            .unwrap_or_else(|e| panic!("{name}: {e}"));

        // Decompressed payload should be comparable to or smaller than file
        // (Snappy decompression produces the payload, file includes varint + padding)
        let ratio = model.program_size() as f64 / file_size as f64;
        println!("  {name:45} file={file_size:>10}  payload={:>10}  ratio={ratio:.2}",
                 model.program_size());

        assert!(
            model.program_size() <= file_size * 2,
            "{name}: decompressed size ({}) is unreasonably larger than file ({file_size})",
            model.program_size()
        );
    }
}

#[test]
#[ignore = "requires baseCamp/zoo-artifacts/*.fbz"]
fn benchmark_parse_throughput() {
    if !zoo_artifacts_available() {
        return;
    }

    let files = collect_fbz_files();
    let mut total_bytes = 0usize;
    let start = std::time::Instant::now();

    for path in &files {
        let model = Model::from_file(path.to_str().unwrap()).unwrap();
        total_bytes += model.program_size();
    }

    let elapsed = start.elapsed();
    let mb = total_bytes as f64 / (1024.0 * 1024.0);
    let mbps = mb / elapsed.as_secs_f64();

    println!("\nParsed {} models ({mb:.2} MB) in {elapsed:.2?} = {mbps:.1} MB/s", files.len());
    assert!(mbps > 1.0, "Parse throughput ({mbps:.1} MB/s) is suspiciously low");
}
